/* eslint-disable */
/**
 * Stub generated by the app scaffold. Replaced when you run `npx convex dev`.
 */
export declare const query: unknown;
export declare const mutation: unknown;
export declare const action: unknown;
export declare const internalQuery: unknown;
export declare const internalMutation: unknown;
export declare const internalAction: unknown;
